config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :memes do
    resources :bookings, only: %i[new create show]
      # member do
      #   patch :accept
      #   patch :reject
      # end
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/requests', to: 'bookings#requests'
  patch '/approve', to: 'bookings#approve'
  patch '/reject', to: 'bookings#reject'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  # root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :meme
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
end

app/models/meme.rb
class Meme < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :title, :category, :price, :photo, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_description_and_category,
    against: [:title, :description, :category],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :memes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @meme = Meme.find(params[:meme_id])
  end

  def show
    @booking = Booking.find(params[:id])
    @meme = Meme.find(params[:meme_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @meme = Meme.find(params[:meme_id])
    @booking.status = 0
    @booking.meme = Meme.find(params[:meme_id])
    @booking.user = current_user
    if @booking.save
      flash[:booking] = "Booking request for #{@booking.meme.title} sent!"
      redirect_to dashboard_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def requests
    @bookings = Booking.where(user_id: current_user)
  end

  def approve
    @booking = Booking.find(params[:format])
    @booking.accepted!
    redirect_to requests_path
  end

  def reject
    @booking = Booking.find(params[:format])
    @booking.rejected!
    redirect_to requests_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  def index
    if params[:query].present?
      sql_query = 'title ILIKE :query OR category ILIKE :query OR description ILIKE :query'
      @memes = Meme.where(sql_query, query: "%#{params[:query]}%")
    else
      @memes = Meme.all
    end
  end

  def show
    @meme = Meme.find(params[:id])
    @bookings = Booking.where(user_id: current_user)
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy
    redirect_to memes_path, status: :see_other
  end

  def new
    @meme = Meme.new
  end

  def create
    @meme = Meme.new(meme_params)
    @meme.user = current_user
    if @meme.save
      redirect_to meme_path(@meme)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @meme = Meme.find(params[:id])
    @meme.title = meme_params[:title]
    @meme.category = meme_params[:category]
    @meme.price = meme_params[:price]
    @meme.save

    redirect_to meme_path(@meme)
  end

  def edit
    @meme = Meme.find(params[:id])
  end

  private

  def meme_params
    params.require(:meme).permit(:title, :category, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @memes = Meme.where(user: current_user)
    @bookings_active = Booking.where(status: 1)
    @bookings_pending = Booking.where(status: 0)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <article>
        <h2 class="mb-5 pb-3">Create booking request for -<br>
          (<%= @meme.title %> Meme)</h2>
      </article>
      <div class="form-container">
        <%= simple_form_for [@meme, @booking] do |f| %>
          <p><small>Start Date</small><br>
            <%= f.text_field :start_date, data: { controller: "flatpickr", flatpickr_date_format: "Y-m-d", flatpickr_mode: "range", flatpickr_min_date: Time.zone.now } %>
          </p>
          <p><small>End Date</small><br>
            <%= f.text_field :end_date, id: "secondRangeInput" %>
            <%# # , data: {
      # controller: "flatpickr",
      # flatpickr_date_format: "Y-m-d",
      # flatpickr_mode: "range",
      # flatpickr_min_date: Time.zone.now} %>

          </p>
          <%= f.button :submit, :class =>"btn purple mt-3" %>
        <% end %>
        <%=  %>
      </div>
    </div>
    <div class="booking-details mb-3 border shadow bg-white">
      <%= cl_image_tag @meme.photo.key %>
    </div>
  </div>
</div>

app/views/bookings/requests.html.erb
<div class="container container-requests">
  <article>
    <h1 class="h1-requests mb-5">Booking Requests</h1>
  </article>
  <div class="row mt-5">
    <% @bookings.each do |booking| %>
      <% if booking.status == "pending" %>
        <div class="col-4">
          <div class="card">
            <%= cl_image_tag "#{booking.meme.photo.key}" %>
            <div class="card-body">
              <h4 class="mb-4">
                <%= booking.meme.title %>
              </h4>
              <div class="d-flex">
                <span class="tag tag-purple mb-4 me-2"><%= booking.meme.category %></span>
                <span class="tag tag-yellow mb-4">Pending</span>
              </div>
              <div class="d-flex icon justify-content-between">
                <%= link_to "", approve_path(booking), data: { turbo_method: :patch }, class: "fa-regular fa-circle-check green-icon fa-2x" %>
                <%= link_to "", reject_path(booking), data: { turbo_method: :patch }, class: "fa-regular fa-circle-xmark red-icon fa-2x" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">

<h2>Booking Request Successfully Created!</h2>
<p>Booking Status for <%= @meme.title %> is <%= @booking.status %></p>
<p>Booking start date: <%= @booking.start_date %></p>
<p>Booking end date: <%= @booking.end_date %></p>
</div>

<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemeMarket</title>
    <link rel="icon" href="https://data.apksum.com/cb/com.jetfuel.colormeme/10.0/icon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/memes/edit.html.erb
<div class="container container-edit">
  <div class="d-flex align-items-start">
    <div class="container-edit-tile1 ">
      <%= cl_image_tag(@meme.photo.key) %>
    </div>
    <div class="container-edit-tile2 ms-4">
      <article class="mb-4">
        <h1><%= @meme.title %></h1>
      </article>
      <%= simple_form_for @meme do |f| %>
        <div class="d-flex">
          <div class="m-1">
            <%= f.input :title %>
          </div>
          <div class="m-1">
            <%= f.input :category %>
          </div>
        </div>
        <div class="m-1">
          <%= f.input :description %>
        </div>
        <div class="d-flex">
          <div class="m-1">
            <%= f.input :photo, as: :file %>
          </div>
          <div class="m-1">
            <%= f.input :price %>
          </div>
        </div>
        <%= f.button :submit, :class =>"btn purple ms-1 mt-2" %>
      <% end %>
    </div>
  </div>

app/views/memes/index.html.erb
<div class="container container-index">
  <article>
    <h1 class="h1-index mt-5">MemeMarket</h1>
    <p class="mb-5 small">What tickles your pickle?</p>
  </article>
  <div class="container container-index-search">
    <%= form_with url: memes_path, method: :get, class: "d-flex rounded-lg" do %>
      <%= text_field_tag :query,
    params[:query],
    class: "form-control search-bar ms-5",
    placeholder: "Find a meme"%>
      <%= submit_tag "Search", class: "btn ms-2 purple" %>
    <% end %>
  </div>
  <div class="container m-0 pt-0 ps-3 pe-3 container-index1">
    <div class="row">
      <% @memes.each do |meme| %>
        <a class="links" href="/memes/<%= meme.id %>">
          <div class="d-flex postcard rounded light blue">
            <%= cl_image_tag meme.photo.key %>
            <div class="postcard__text t-dark">
              <div class="postcard__subtitle small">
                <h1 class="postcard__title"><%= meme.title %></h1>
              </div>
              <div class="postcard__bar"></div>
              <div class="postcard__body">
                <i class="fa-solid fa-dollar-sign large"></i> <%= meme.price %>
              </div>
            </div>
            <div class="ribbon"><span class="ribbon__content"><%= meme.category %></span></div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/memes/new.html.erb
<div class="container">
  <article>
    <h1 class="h1-new-meme ps-2 ms-5">Create a new Meme</h1>
  </article>
  <div class="d-flex form-new mb-3 p-5">
    <div class="col-12 me-5">
      <%= simple_form_for @meme do |f| %>
        <div class="d-flex">
          <div class="m-2">
            <%= f.input :title %>
          </div>
          <div class="m-2">
            <%= f.input :category %>
          </div>
          <div class="m-2">
            <%= f.input :price %>
          </div>
        </div>
        <div class="m-2 ">
          <%= f.input :description %>
        </div>
        <div class="d-flex justify-content-between">
          <div class="m-2">
            <%= f.input :photo, as: :file %>
          </div>
          <%= f.button :submit, :class =>"btn purple mt-5 mb-5" %>
        </div>
      <% end %>
    </div>
  <div class="col-3 new-meme-image"></div>
  </div>
</div>

app/views/memes/show.html.erb
<div class="container container-show">
  <div class="d-flex align-items-start">
    <div class="container-show-tile1 m-2">
      <%= cl_image_tag(@meme.photo.key) %>
      <div class="container ms-0 ps-0 justify-content-end">
      </div>
    </div>
    <div class="container-show-tile2 ms-5">
      <article>
        <div class="d-flex mt-4 mb-4">
          <h1><%= @meme.title %></h1>
        </div>
      </article>
      <div class="d-flex">
        <p class="badge card-price green me-2">$<%= @meme.price %></p>
        <p class="badge purple ms-2 me-2"><%= @meme.category %></p>
        <% @bookings.each do |booking| %>
          <% if booking.meme_id == @meme.id  && booking.status == 'pending' %>
            <p class="badge tag-yellow ms-2 me-2">Pending</p>
          <% end %>
          <% if booking.meme_id == @meme.id  && booking.status == 'accepted' %>
            <p class="badge tag-green ms-2 me-2">Active</p>
          <% end %>
        <% end %>
      </div>
      <p class="mt-4 desc"><%= @meme.description %></p>
      <div class="ms-0">
        <%= link_to '', "/memes/#{@meme.id}/bookings/new", class: "fa-regular fa-calendar blue-text me-5 mt-5 pt-5" %>
        <% if @meme.user == current_user %>
          <%= link_to '', "/memes/#{@meme.id}/edit", class: "fa-solid fa-pen-to-square yellow-text me-5 ms-3" %>
          <%= link_to '', meme_path(@meme), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "fa-regular fa-trash-can purple-text ms-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="container">
  <h1>About</h1>
  <% raise %>
</div>

app/views/pages/dashboard.html.erb
<div class="container container-dashboard">
  <article>
    <h1 class="h1-index mb-5 mt-5 pb-5">Dashboard</h1>
  </article>
  <div class="accordion accordion-dashboard" id="accordionExample">
    <div class="accordion-item bckg-color">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          My Memes
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <%= link_to "Add", new_meme_path(), class: "fa-solid btn purple fa-plus pe-3 ms-4 mt-4"%>
      <div class="accordion-body">
        <div class="row">
          <% @memes.each do |meme| %>
            <div class="col-4">
              <a href="/memes/<%= meme.id %>">
                <div class="card">
                  <%= cl_image_tag "#{meme.photo.key}" %>
                  <div class="card-body">
                    <span class="tag tag-purple mb-4"><%= meme.category %></span>
                    <h4>
                      <%= meme.title %>
                    </h4>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item bckg-color">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Pending Requests
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <div class="row">
          <% @bookings_pending.each do |booking| %>
            <div class="col-4">
              <a href="/memes/<%= booking.meme.id %>">
                <div class="card">
                  <%= cl_image_tag "#{booking.meme.photo.key}" %>
                  <div class="card-body">
                    <div class="d-flex">
                      <span class="tag tag-purple mb-4 me-2"><%= booking.meme.category %></span>
                      <span class="tag tag-yellow mb-4">Pending</span>
                    </div>
                    <h4>
                      <%= booking.meme.title %>
                    </h4>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item bckg-color">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Active Bookings
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <div class="row">
          <% @bookings_active.each do |booking| %>
            <div class="col-4">
              <a href="/memes/<%= booking.meme.id %>">
                <div class="card">
                  <%= cl_image_tag "#{booking.meme.photo.key}" %>
                  <div class="card-body">
                    <div class="d-flex">
                      <span class="tag tag-purple mb-4 me-2"><%= booking.meme.category %></span>
                      <span class="tag tag-green mb-4">Approved</span>
                    </div>
                    <h4>
                      <%= booking.meme.title %>
                    </h4>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid home-banner text-left vh-65 container-home">
  <div class="row h-100">
    <div class="row justify-content-around align-items-center">
      <!-- Left Side of Banner-->
      <div class="col-4 justify-content-center">
        <div>
          <h1>Discover, curate & license dank memes</h1>
          <h2 class="my-4">MemeMarket is LeWagon's premiere source of the <strong>Impact</strong> font</h2>
        </div>
        <div class="row">
          <div class="arrow col-3 m ms-5">
            <div class="indicator">
              <span></span>
              <span></span>
              <span></span>
              <span></span>
              <span></span>
              <span></span>
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
          <a class="col-5" href="/memes">
            <div class="btn purple rounded-lg home-text"><strong>Get Started!</strong></div>
          </a>
        </div>
      </div>
      <!-- Right Side of Banner-->
      <div class="col-4 justify-content-center">
        <div class="card" style="width: 25rem;">
          <img src="https://c.tenor.com/7Tu-pBzg0_kAAAAC/programming.gif" class="card-img-top" alt="Everything is fine.">
          <div class="card-body">
            <h5 class="card-title">Everything is fine.</h5>
            <p class="card-text">It's not a problem if it's not production right?</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>
<% if flash[:booking] %>
  <div class="alert alert-warning alert-dismissible fade show m-1 success-flash" role="alert">
    <button type="button" class="btn-close" id="btn-close-success" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:booking] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container container-footer">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/home" class="nav-link px-3">Home</a></li>
      <li class="nav-item"><a href="/memes" class="nav-link px-3">Marketplace</a></li>
      <li class="nav-item"><a href="/about" class="nav-link px-3">About</a></li>
    </ul>
    <p class="text-center"> <i class="fa-solid fa-code"></i></p>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-meme">
  <div class="container-fluid">
    <a class="d-flex justify-content-start align-items-center" href="/home">
      <div class="navbar-brand"></div>
      <article><h4 class="mt-2">MemeMarket</h4></article>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item nav-item-bar active">
            <%= link_to "Home", "/home", class: "nav-link" %>
          </li>
          <li class="nav-item nav-item-bar">
            <%= link_to "Dashboard", "/dashboard", class: "nav-link" %>
          </li>
          <li class="nav-item nav-item-bar">
            <%= link_to "Marketplace", "/memes", class: "nav-link" %>
          </li>
          <li class="nav-item nav-item-drop dropdown">
            <%= image_tag "https://ps.w.org/wpdevart-vertical-menu/assets/icon-128x128.png?rev=2584189", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "View Profile", "/dashboard", class: "dropdown-item" %>
              <%= link_to "Marketplace", "/", class: "dropdown-item" %>
              <%= link_to "Add a new meme", new_meme_path, class: "dropdown-item" %>
              <%= link_to "View booking Requests", requests_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>